<#import "blocks/general.ftlh" as g>

<@g.page>
    <div class="container text-center mt-3">
        <h3>Hello, a member of our extended family named "COMPANY NAME"!</h3>
    </div>
    <div class="container text-center mt-3">
        <h4>Our company have more interesting and helpful information! This day will be important for you!
        Have a good mood and more energy for your daily work!</h4>
    </div>
</@g.page>